apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-sample-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-sample-app
    spec:
      containers:
        - name: nginx-sample-app
          image: nginx:1.23.1-alpine
          ports:
            - name: http-port
              containerPort: 80
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-sample-app
spec:
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx-sample-app
  sessionAffinity: None
  type: ClusterIP
